version: 2
updates:
  # Maintain GitHub Action dependencies.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain go module dependencies.
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
