---
name: Lint

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - master
  schedule:
    - cron: '00 18 * * 4'

permissions:
  contents: read

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.44.0
